blank_issues_enabled: true
contact_links:
  - name: "Hugo Discussions"
    url: https://github.com/Mavioni/Hugo-M-/discussions
    about: Ask questions, share ideas, and discuss Hugo with the community.
